<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>KSoft.Phoenix</RootNamespace>
    <AssemblyName>KSoft.Phoenix</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft\KSoft.csproj">
      <Project>{eb07f515-e27c-4768-8bd8-2829f657807e}</Project>
      <Name>KSoft</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Compression\KSoft.Compression.csproj">
      <Project>{0b27603c-ceb1-4a3a-b56f-cbc14b8c06e7}</Project>
      <Name>KSoft.Compression</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.IO.TagElementStreams\KSoft.IO.TagElementStreams.csproj">
      <Project>{18f32228-8351-4f99-992f-78e9d1ce83d9}</Project>
      <Name>KSoft.IO.TagElementStreams</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Security\KSoft.Security.csproj">
      <Project>{0632a00b-de9e-4350-a3f8-3a82f9c780af}</Project>
      <Name>KSoft.Security</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)Games\Wwise\KSoft.Wwise\KSoft.Wwise.csproj">
      <Project>{bddec955-6d39-4058-92e5-f1bf170f860f}</Project>
      <Name>KSoft.Wwise</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Math\KSoft.Math.csproj">
      <Project>{423f13fc-da0c-4c82-b75e-60a1bfea7bb6}</Project>
      <Name>KSoft.Math</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.PropertyChanged.SourceGeneration\KSoft.PropertyChanged.SourceGeneration.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="False"
                      PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Content
        Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.dll"
        Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.dll')"
        >
      <Link>DDS\DirectXTexDLL.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content
        Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.pdb"
        Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.pdb')"
        >
      <Link>DDS\DirectXTexDLL.pdb</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content
        Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DDSView.exe"
        Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DDSView.exe')"
        >
      <Link>DDS\DDSView.exe</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content
        Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\texconv.exe"
        Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\texconv.exe')"
        >
      <Link>DDS\texconv.exe</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
