<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Test.KSoft.Phoenix</RootNamespace>
    <AssemblyName>Test.KSoft.Phoenix</AssemblyName>
    <CodeContractsAssemblyMode>1</CodeContractsAssemblyMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft\KSoft.csproj">
      <Project>{eb07f515-e27c-4768-8bd8-2829f657807e}</Project>
      <Name>KSoft</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.IO.TagElementStreams\KSoft.IO.TagElementStreams.csproj">
      <Project>{18f32228-8351-4f99-992f-78e9d1ce83d9}</Project>
      <Name>KSoft.IO.TagElementStreams</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Security\KSoft.Security.csproj">
      <Project>{0632a00b-de9e-4350-a3f8-3a82f9c780af}</Project>
      <Name>KSoft.Security</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)Games\Wwise\KSoft.Wwise\KSoft.Wwise.csproj">
      <Project>{bddec955-6d39-4058-92e5-f1bf170f860f}</Project>
      <Name>KSoft.Wwise</Name>
    </ProjectReference>
    <ProjectReference Include="..\KSoft.Phoenix\KSoft.Phoenix.csproj">
      <Project>{3fd3a05a-4451-49d1-b38e-b897f3444754}</Project>
      <Name>KSoft.Phoenix</Name>
    </ProjectReference>
  </ItemGroup>
  <!-- NOTE: Need to use x86 versions since unit tests are ran inside VS, and x64 DLLs result in exceptions saying it tried to load a bad image-->
  <!--Except VS2022 is 64-bit! So, we're running with x64-->
  <ItemGroup>
    <Content
      Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.dll"
      Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.dll')"
      >
      <Link>DDS\DirectXTexDLL.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content
      Include="$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.pdb"
      Condition="Exists('$(VitaRootDir)shared\external_libraries\DirectXTex\x64\DirectXTexDLL.pdb')"
      >
      <Link>DDS\DirectXTexDLL.pdb</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
